make: main.c helpers.c ls.c cd.c rm.c lseek.c read.c cmdopen.c cmdclose.c size.c info.c exit.c
	gcc main.c helpers.c ls.c cd.c rm.c lseek.c read.c cmdopen.c size.c info.c exit.c cmdclose.c -std=c11 -o Project3
