make: main.c helpers.c ls.c cd.c rm.c lseek.c read.c creatt.c mkdirr.c cmdopen.c cmdclose.c info.c size.c exit.c
	gcc main.c helpers.c ls.c cd.c rm.c lseek.c read.c creatt.c mkdirr.c cmdopen.c cmdclose.c info.c size.c exit.c -std=c11 -o Project3
debug: main.c helpers.c ls.c cd.c rm.c lseek.c read.c creatt.c mkdirr.c cmdopen.c cmdclose.c info.c size.c exit.c
	gcc -g -w main.c helpers.c ls.c cd.c rm.c lseek.c read.c creatt.c mkdirr.c cmdopen.c cmdclose.c info.c size.c exit.c -std=c11
